server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ENC(idIWCdznEM3ggslDeTmLJw==)
    key-store-type: PKCS12
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  messages:
    basename: message
    encoding: utf-8
    cache-duration: 10
    fallback-to-system-locale: false
  config:
    import: optional:file:.env[.properties]
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/shopdb?characterEncoding=utf8
#    username: root
#    password: ENC(idIWCdznEM3ggslDeTmLJw==)
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ENC(idIWCdznEM3ggslDeTmLJw==)

mybatis:
  type-aliases-package: edu.sm.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info

app:
  url:
    websocketurl: https://127.0.0.1:8443/
  dir:
    imgsdir: file:///C:/smspring/imgs/
    uploadimgsdir: C:/smspring/imgs/
    logsdir: file:///C:/smspring/logs/
    logsdirRead: C:/smspring/logs/
  key:
    skey: ${MY_KEY}
    algo: PBEWithMD5AndDES
    wkey: ENC(ujBA1JACJu2p9j6zX+vrd9p/ZPho16chYvfNoOC8Ski8LQhp96WvomTXolMJypABjEjam/nslEfM0eA3zyKi4cxNTk9BseWFAbWXrJ2HPkA=)
    owkey: ENC(vIqd9CSeOJ2B+RNZB8q8uX2gqVeotK1BVjLTnpvApIu0QKfrK4PIS+zKhZuQbERZ)